DROP TABLE Users IF EXISTS CASCADE;
DROP TABLE Provision IF EXISTS CASCADE;
DROP TABLE Sales IF EXISTS CASCADE;

CREATE TABLE Users (
	id_user char(128),
	amount float,
	firstname CHAR(30),
	lastname CHAR(30),
	primary key(id_user)
)

CREATE TABLE Provision (
	id_drink int,
	name char(30),
	price float,
	primary key(id_drink)
)

CREATE TABLE sales (
	id_sale INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
	time timestamp,
	terminal int,
	id_drink int,
    quantity int,
	id_user char(128),
	primary key(id_sale),
	foreign key(id_drink) references Provision(id_drink) on delete set null on update CASCADE,
	foreign key(id_user) references Users(id_user) on delete set null on update CASCADE
)
